name: Demo XLL Perftest

permissions:
  contents: write
  actions: read
  checks: write

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: xllify Luau perftest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: xllify luau
        id: xllify
        uses: xllifycom/xllify-build@v0.9.6
        with:
          xll_filename: xllify_perftest_luau
          embed_scripts: |
            perftest/luau/random.luau
          xllify_key: earlyadopter

      - name: Write signing file
        shell: pwsh
        run: |
          $pfxBytes = [Convert]::FromBase64String("${{ secrets.XLLIFY_PFX_BASE64 }}")
          [IO.File]::WriteAllBytes("xllify.pfx", $pfxBytes)
          
      - name: Self sign
        shell: pwsh
        run: |
          $signtool = Get-ChildItem -Path "C:\Program Files (x86)\Windows Kits" -Recurse -Filter "signtool.exe" | Select-Object -First 1
          & $signtool.FullName sign /fd SHA256 /f xllify.pfx /p ${{ secrets.XLLIFY_PW }} /t http://timestamp.digicert.com ${{ steps.xllify.outputs.xll_path }}

      - name: Upload XLL to workflow job
        uses: actions/upload-artifact@v4
        with:
          name: xllify_perftest_luau
          path: ${{ steps.xllify.outputs.xll_path }}

      - name: Upload XLL to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.xllify.outputs.xll_path }}
  
  build_py:
    name: xllify Python perftest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: xllify
        id: xllify
        uses: xllifycom/xllify-build@v0.9.6
        with:
          xll_filename: xllify_perftest_python
          embed_scripts: |
            perftest/python/perftest.py
          xllify_key: earlyadopter
          python_requirements: perftest/python/requirements.txt

      - name: Upload XLL to workflow job
        uses: actions/upload-artifact@v4
        with:
          name: xllify_perftest_python
          path: ${{ steps.xllify.outputs.xll_path }}

      - name: Upload XLL to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.xllify.outputs.xll_path }}
